# Data Cleaning Intro

In [1]:
import numpy as np
import pandas as pd

In [2]:
falsy_values = (0, False, None, '', [], {}) # in python these are considered falsy values
any(falsy_values)

False

In [5]:
print(np.nan) # NaN ruins everything, same with inf
print(3 + np.nan) # None will raise an exception
a = np.array([1, 2, 3, np.nan, np.nan, 4])
a.sum()

nan
nan


nan

In [7]:
np.inf

inf

### Checking for Bad Values

#### NumPy

In [10]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))
print(np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4])))
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4])) # joint of nan and inf

[False False False False  True False]


array([ True,  True,  True, False, False,  True])

In [11]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])
a[~np.isnan(a)] # filter out

array([1., 2., 3., 4.])

In [12]:
a[np.isfinite(a)] # same as 

array([1., 2., 3., 4.])

#### Pandas

In [13]:
pd.isnull(pd.DataFrame({
    'Column A': [1, np.nan, 7],
    'Column B': [np.nan, 2, 3],
    'Column C': [np.nan, 2, np.nan]
}))
# pd.notnull
# pd.notna()
# pd.isna()

Column A  Column B  Column C
0     False      True      True
1      True     False     False
2     False     False      True

In [14]:
pd.Series([1, 2, np.nan]).sum() # Pandas handles missing values unlike NumPy

3.0

In [15]:
s = pd.Series([1, 2, 3, np.nan, np.nan, 4]);s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [18]:
s[pd.notnull(s)] # or 
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

### Dropping null Values on DataFrames
Gotta be more careful as you can only drop rows or columns and not indivual values

In [20]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
}); df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [21]:
df.isnull()

Column A  Column B  Column C  Column D
0     False     False      True     False
1      True     False     False     False
2     False     False     False     False
3      True      True     False     False

In [22]:
df.isnull().sum()

Column A    2
Column B    1
Column C    1
Column D    0
dtype: int64

In [24]:
df.dropna() # Will drop any rows that contain na values
df.dropna(axis=1)  # axis='columns' also works

Column D
0         5
1         8
2        34
3       110

In [27]:
df.dropna(thresh=3) # Same but can set threshold before removing

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34

### Filling null Values on Series

In [28]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [29]:
s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
4    0.0
5    4.0
dtype: float64

In [30]:
s.fillna(s.mean())

0    1.0
1    2.0
2    3.0
3    2.5
4    2.5
5    4.0
dtype: float64

In [31]:
s.fillna(method='ffill')

0    1.0
1    2.0
2    3.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [32]:
s.fillna(method='bfill')

0    1.0
1    2.0
2    3.0
3    4.0
4    4.0
5    4.0
dtype: float64

### Filling null Values on DataFrames

In [33]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [34]:
df.fillna({'Column A': 0, 'Column B': 99, 'Column C': df['Column C'].mean()})

Column A  Column B  Column C  Column D
0       1.0       2.0      47.0         5
1       0.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3       0.0      99.0     100.0       110

### Checking if there are NAs

In [35]:
s.dropna().count()

4

In [36]:
missing_values = len(s.dropna()) != len(s); missing_values

True

In [37]:
# Python has in built solution using any() and all()
pd.Series([True, False, False]).any()
pd.Series([True, False, False]).all()

False

In [38]:
pd.Series([1, np.nan]).isnull().any()

True