## NumPy Overview 
Refresher on these core analysis packages for myself :)

### NumPy
Is a library that is used for numeric processing. Is used because it is very efficent library that scales well. NumPy is an Array processing library. 

Because python is a high level language simple operations take a lot more memory than is needed. Wheres NumPy better allocates memory. 

In [3]:
import sys
import numpy as np

In [6]:
# same as list but using np.array()
a = np.array([1, 2, 3, 4])
b = np.array([0, .5, 1, 1.5, 2])
# main difference is multi indexing into another array
b[[0,2,-1]]

array([0., 1., 2.])

In [9]:
# sets default types
a.dtype
b.dtype
# can set 
np.array([1, 2, 3, 4], dtype=np.float)

array([1., 2., 3., 4.])

#### Dimensions

In [11]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
]); A

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
A.shape

(2, 3)

In [13]:
A.ndim

2

In [15]:
A.size

6

#### Index and Slice Matrices

In [17]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [21]:
# If you want to get 4 you can 
A[1][0]
# or
A[1,0] #row/column

4

In [22]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [23]:
# adjusting 
A[1] = np.array([10, 10, 10])
# or
A[2] = 99
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#### Summary Statistics

In [28]:
A.mean()
A.std()
A.sum(axis=0) # 0=col, 1=row

array([110, 111, 112])

#### Broadcasting and Vectorized Operations

In [42]:
a = np.arange(4); a

array([0, 1, 2, 3])

In [36]:
# to each one of elements within do...
a + 10 # also results in a NEW array

array([10, 11, 12, 13])

In [38]:
# to modify 
a += 10; a

array([20, 21, 22, 23])

In [39]:
# base python this would be 
l = [0, 1, 2, 3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [44]:
b = np.array([10, 10, 10, 10])
a + b

array([10, 11, 12, 13])

In [45]:
a * b

array([ 0, 10, 20, 30])

#### Boolean Arrays (important to know well)

In [47]:
a = np.arange(4); a

array([0, 1, 2, 3])

In [48]:
# another method for selecting elements
a[[True, False, False, True]]

array([0, 3])

In [49]:
a[a >= 2]

array([2, 3])

In [52]:
a[(a == 0) | (a == 1)] # or and 
a[~(a > a.mean())] # not greater than mean

array([0, 1])

#### Linear Algebra 

In [55]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [6, 5],
    
    [4, 3],
    [2, 1]
])

In [57]:
A.dot(B) # dot product
A @ B # cross product 
B.T # Transpose 

array([[6, 4, 2],
       [5, 3, 1]])

#### Size of Objects in Memory

In [58]:
sys.getsizeof(1)

28

In [59]:
np.dtype(int).itemsize
np.dtype(float).itemsize

8

In [61]:
sys.getsizeof([1])

72

In [62]:
np.array([1]).nbytes

8

In [66]:
l = list(range(100000))
%time sum([x ** 2 for x in l])

CPU times: user 39.6 ms, sys: 6.91 ms, total: 46.5 ms
Wall time: 47.1 ms


333328333350000

In [65]:
a = np.arange(100000)
%time np.sum(a ** 2)

CPU times: user 662 µs, sys: 534 µs, total: 1.2 ms
Wall time: 1.42 ms


333328333350000

#### Useful Numpy Functions

##### random

In [67]:
np.random.random(size=2)

array([0.54667691, 0.13827583])

In [68]:
np.random.normal(size=2)

array([-0.35382765,  0.45337194])

In [69]:
np.random.rand(2, 4)

array([[0.81542305, 0.69025315, 0.45163038, 0.68540234],
       [0.43840816, 0.1112298 , 0.37611999, 0.92796137]])

##### arange

In [70]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [72]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [73]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### linespace

In [74]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [75]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

##### zeros, ones, empty

In [76]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [77]:
np.zeros((3, 3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [79]:
np.ones((3, 3))
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

##### idendity and eye

In [80]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])